export interface Product {
  id: string;
  title: string;
  category: string;
  image: string;
  price: number;
  description: string;
  collection: string;
}

export const shopProducts: Product[] = [
  {
    id: "big-bend-wild-horses",
    title: "Wild Horses of Big Bend",
    category: "Prints",
    image: "/images/world-lens/Big Bend National Park, Texas/0bac9d96-b622-453a-be16-80de4506f6e4_rw_1920.jpg",
    price: 189,
    description: "Majestic wild mustangs roaming free in the dramatic Texas landscape. Museum-quality giclée print on archival paper.",
    collection: "World Through My Lens",
  },
  {
    id: "white-sands-dunes",
    title: "White Sands Serenity",
    category: "Prints",
    image: "/images/world-lens/White Sands National Park, New Mexico/0444d443-61f2-4036-a528-a51643d9d672_rw_1920.jpg",
    price: 199,
    description: "The otherworldly beauty of New Mexico's white gypsum dunes. Limited edition fine art print.",
    collection: "World Through My Lens",
  },
  {
    id: "iditarod-adventure",
    title: "Iditarod: The Last Great Race",
    category: "Prints",
    image: "/images/world-lens/Iditarod, Alaska/0a2c4313-37cb-429f-acaf-f6ad40735097_rw_1920.jpg",
    price: 179,
    description: "Capturing the spirit of Alaska's legendary dog sled race. Premium quality archival print.",
    collection: "World Through My Lens",
  },
  {
    id: "balloon-fiesta-colors",
    title: "Balloon Fiesta Magic",
    category: "Prints",
    image: "/images/world-lens/Balloon Fiesta, New Mexico/00490719-d6fd-4b26-ac92-ac443e3db926_rw_1920.jpg",
    price: 169,
    description: "Hundreds of colorful hot air balloons painting the New Mexico sky at dawn.",
    collection: "World Through My Lens",
  },
  {
    id: "black-white-expression",
    title: "Monochrome Majesty",
    category: "Prints",
    image: "/images/perspectives/Black&White/04c630a6-0dbe-447c-8f39-be082ae74df5_rw_1200.jpg",
    price: 149,
    description: "Timeless black and white photography showcasing dramatic contrast and emotion.",
    collection: "Captured Perspectives",
  },
  {
    id: "oil-country-industrial",
    title: "Oil Country Heritage",
    category: "Prints",
    image: "/images/perspectives/Oil Country/124c9218-c74b-4bf3-bc25-1d6b8bfb5c61_rw_1200.jpg",
    price: 159,
    description: "Finding beauty in Texas industrial landscapes. Bold, artistic interpretation.",
    collection: "Captured Perspectives",
  },
  {
    id: "maternity-portrait",
    title: "Anticipation",
    category: "Prints",
    image: "/images/unspoken/Maternity/157f88b0-4f8a-460c-9eb0-bd9a03228cf6_rw_1200.jpg",
    price: 139,
    description: "Celebrating the beauty of motherhood. Elegant maternity portrait fine art print.",
    collection: "Unspoken",
  },
  {
    id: "newborn-innocence",
    title: "New Beginnings",
    category: "Prints",
    image: "/images/unspoken/Baby Photoshoot/08c449d2-3d74-4891-8b11-54cdc615f89d_rw_1200.jpg",
    price: 129,
    description: "The precious beauty of a newborn's first days. Tender and timeless.",
    collection: "Unspoken",
  },
  {
    id: "shadows-artistic",
    title: "Light and Shadow",
    category: "Prints",
    image: "/images/unspoken/Shadows/0bc0d256-f0a5-487d-a406-f3ebcd1472aa_rw_1200.jpg",
    price: 149,
    description: "Artistic interpretation through dramatic shadows and light. Contemporary fine art.",
    collection: "Unspoken",
  },
  {
    id: "world-lens-book",
    title: "The World Through My Lens - Photobook",
    category: "Photobooks",
    image: "/images/world-lens/Big Bend National Park, Texas/1b6ad388-01d3-4484-a14f-90398e73e698_rw_1920.jpg",
    price: 129,
    description: "150-page hardcover collection featuring 733 photographs from 20 locations across America and beyond.",
    collection: "World Through My Lens",
  },
  {
    id: "perspectives-book",
    title: "Captured Perspectives - Photobook",
    category: "Photobooks",
    image: "/images/perspectives/LandScape/c1474280-d99c-491f-a321-a9009a2a5c3d.jpg",
    price: 99,
    description: "Artistic vision through 5 unique categories. 120 pages of curated photography.",
    collection: "Captured Perspectives",
  },
  {
    id: "unspoken-book",
    title: "Unspoken: Life's Precious Moments",
    category: "Photobooks",
    image: "/images/unspoken/Portraits/023140e6-f8e1-4e66-a89f-ee346dbacfeb_rw_1200.jpg",
    price: 89,
    description: "Portrait photography celebrating life stages from newborns to seniors. 100 pages of emotion.",
    collection: "Unspoken",
  },
  {
    id: "revelations-digital",
    title: "Recent Revelations - Digital Collection",
    category: "Digital Downloads",
    image: "/images/revelations/Prague - Czech Republic/0d73fbe7-c3c7-4a77-95ad-c83a9180162c_rw_1920.jpg",
    price: 49,
    description: "50 high-resolution images from 9 international destinations. Digital download package.",
    collection: "Recent Revelations",
  },
  {
    id: "nature-digital",
    title: "Nature's Grandeur - Digital Pack",
    category: "Digital Downloads",
    image: "/images/perspectives/Nature/0dae414e-aff8-446f-9f8b-f26987a17d3c_rw_1200.jpg",
    price: 39,
    description: "25 stunning nature and landscape photographs. High-resolution digital files.",
    collection: "Captured Perspectives",
  },
  {
    id: "black-white-digital",
    title: "Monochrome Collection - Digital",
    category: "Digital Downloads",
    image: "/images/perspectives/Black&White/06ae50b9-aa37-4f1d-bf39-cb8a3996a449_rw_1200.jpg",
    price: 35,
    description: "20 powerful black and white images. Perfect for wallpapers and personal projects.",
    collection: "Captured Perspectives",
  },
];
