export interface Product {
  id: string;
  title: string;
  category: string;
  image: string;
  price: number;
  description: string;
  collection: string;
}

export const shopProducts: Product[] = [
  {
    id: "big-bend-wild-horses",
    title: "Wild Horses of Big Bend",
    category: "Prints",
    image: "https://imagedelivery.net/v_WuhwGIT0Zeg5Rlb5xL8Q/images-world-lens-big-bend-national-park-texas-0bac9d96-b622-453a-be16-80de4506f6e4-rw-1920.jpg/public",
    price: 189,
    description: "Majestic wild mustangs roaming free in the dramatic Texas landscape. Gallery-quality giclée print on archival paper.",
    collection: "World Through My Lens",
  },
  {
    id: "white-sands-dunes",
    title: "White Sands Serenity",
    category: "Prints",
    image: "https://imagedelivery.net/v_WuhwGIT0Zeg5Rlb5xL8Q/images-world-lens-white-sands-national-park-new-mexico-0444d443-61f2-4036-a528-a51643d9d672-rw-1920.jpg/public",
    price: 199,
    description: "The otherworldly beauty of New Mexico's white gypsum dunes. Limited edition fine art print.",
    collection: "World Through My Lens",
  },
  {
    id: "iditarod-adventure",
    title: "Iditarod: The Last Great Race",
    category: "Prints",
    image: "https://imagedelivery.net/v_WuhwGIT0Zeg5Rlb5xL8Q/images-world-lens-iditarod-alaska-0a2c4313-37cb-429f-acaf-f6ad40735097-rw-1920.jpg/public",
    price: 179,
    description: "Capturing the spirit of Alaska's legendary dog sled race. Premium quality archival print.",
    collection: "World Through My Lens",
  },
  {
    id: "balloon-fiesta-colors",
    title: "Balloon Fiesta Magic",
    category: "Prints",
    image: "https://imagedelivery.net/v_WuhwGIT0Zeg5Rlb5xL8Q/images-world-lens-balloon-fiesta-new-mexico-00490719-d6fd-4b26-ac92-ac443e3db926-rw-1920.jpg/public",
    price: 169,
    description: "Hundreds of colorful hot air balloons painting the New Mexico sky at dawn.",
    collection: "World Through My Lens",
  },
  {
    id: "black-white-expression",
    title: "Monochrome Majesty",
    category: "Photo-Inspired Goods",
    image: "https://imagedelivery.net/v_WuhwGIT0Zeg5Rlb5xL8Q/images-perspectives-black-white-04c630a6-0dbe-447c-8f39-be082ae74df5-rw-1200.jpg/public",
    price: 149,
    description: "Timeless black and white photography showcasing dramatic contrast and emotion.",
    collection: "Captured Perspectives",
  },
  {
    id: "industrial-pastures-industrial",
    title: "Industrial Pastures Heritage",
    category: "Photo-Inspired Goods",
    image: "https://imagedelivery.net/v_WuhwGIT0Zeg5Rlb5xL8Q/images-perspectives-oil-country-124c9218-c74b-4bf3-bc25-1d6b8bfb5c61-rw-1200.jpg/public",
    price: 159,
    description: "Finding beauty in Texas industrial landscapes. Bold, artistic interpretation.",
    collection: "Captured Perspectives",
  },
  {
    id: "maternity-portrait",
    title: "Anticipation",
    category: "Prints",
    image: "https://imagedelivery.net/v_WuhwGIT0Zeg5Rlb5xL8Q/images-unspoken-maternity-157f88b0-4f8a-460c-9eb0-bd9a03228cf6-rw-1200.jpg/public",
    price: 139,
    description: "Celebrating the beauty of motherhood. Elegant maternity portrait fine art print.",
    collection: "Unspoken",
  },
  {
    id: "newborn-innocence",
    title: "New Beginnings",
    category: "Prints",
    image: "https://imagedelivery.net/v_WuhwGIT0Zeg5Rlb5xL8Q/images-unspoken-baby-photoshoot-08c449d2-3d74-4891-8b11-54cdc615f89d-rw-1200.jpg/public",
    price: 129,
    description: "The precious beauty of a newborn's first days. Tender and timeless.",
    collection: "Unspoken",
  },
  {
    id: "shadows-artistic",
    title: "Light and Shadow",
    category: "Prints",
    image: "https://imagedelivery.net/v_WuhwGIT0Zeg5Rlb5xL8Q/images-unspoken-shadows-0bc0d256-f0a5-487d-a406-f3ebcd1472aa-rw-1200.jpg/public",
    price: 149,
    description: "Artistic interpretation through dramatic shadows and light. Contemporary fine art.",
    collection: "Unspoken",
  },
  {
    id: "world-lens-book",
    title: "The World Through My Lens - Photobook",
    category: "Photobooks",
    image: "https://imagedelivery.net/v_WuhwGIT0Zeg5Rlb5xL8Q/images-world-lens-big-bend-national-park-texas-1b6ad388-01d3-4484-a14f-90398e73e698-rw-1920.jpg/public",
    price: 129,
    description: "150-page hardcover collection featuring 733 photographs from 20 locations across America and beyond.",
    collection: "World Through My Lens",
  },
  {
    id: "perspectives-book",
    title: "Captured Perspectives - Photobook",
    category: "Photobooks",
    image: "https://imagedelivery.net/v_WuhwGIT0Zeg5Rlb5xL8Q/images-perspectives-landscape-c1474280-d99c-491f-a321-a9009a2a5c3d.jpg/public",
    price: 99,
    description: "Artistic vision through 5 unique categories. 120 pages of curated photography.",
    collection: "Captured Perspectives",
  },
  {
    id: "unspoken-book",
    title: "Unspoken: Life's Precious Moments",
    category: "Photobooks",
    image: "https://imagedelivery.net/v_WuhwGIT0Zeg5Rlb5xL8Q/images-unspoken-portraits-023140e6-f8e1-4e66-a89f-ee346dbacfeb-rw-1200.jpg/public",
    price: 89,
    description: "Portrait photography celebrating life stages from newborns to seniors. 100 pages of emotion.",
    collection: "Unspoken",
  },
  {
    id: "revelations-digital",
    title: "Recent Revelations - Digital Collection",
    category: "Digital Downloads",
    image: "https://imagedelivery.net/v_WuhwGIT0Zeg5Rlb5xL8Q/images-revelations-prague---czech-republic-0d73fbe7-c3c7-4a77-95ad-c83a9180162c-rw-1920.jpg/public",
    price: 49,
    description: "50 high-resolution images from 9 international destinations. Digital download package.",
    collection: "Recent Revelations",
  },
  {
    id: "nature-digital",
    title: "Nature's Grandeur - Digital Pack",
    category: "Digital Downloads",
    image: "https://imagedelivery.net/v_WuhwGIT0Zeg5Rlb5xL8Q/images-perspectives-nature-0dae414e-aff8-446f-9f8b-f26987a17d3c-rw-1200.jpg/public",
    price: 39,
    description: "25 stunning nature and landscape photographs. High-resolution digital files.",
    collection: "Captured Perspectives",
  },
  {
    id: "black-white-digital",
    title: "Monochrome Collection - Digital",
    category: "Digital Downloads",
    image: "https://imagedelivery.net/v_WuhwGIT0Zeg5Rlb5xL8Q/images-perspectives-black-white-06ae50b9-aa37-4f1d-bf39-cb8a3996a449-rw-1200.jpg/public",
    price: 35,
    description: "20 powerful black and white images. Perfect for wallpapers and personal projects.",
    collection: "Captured Perspectives",
  },
];
